// <auto-generated />
using System;
using G64.PedidoAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G64.PedidoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240522020930_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("G64.PedidoAPI.Models.ItemPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItensPedidos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4111eadd-a800-432b-a0c0-c310f8a39b7f"),
                            Descricao = "Combo Whopper",
                            PrecoUnitario = 15.99m,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("1ba15591-fc3b-4613-8aa3-051e6e60e17d"),
                            Descricao = "Coca-cola",
                            PrecoUnitario = 5.99m,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("272e6795-a488-4d52-a28c-363044567ef9"),
                            Descricao = "Batata Frita",
                            PrecoUnitario = 7.99m,
                            Quantidade = 1
                        },
                        new
                        {
                            Id = new Guid("900d293e-6190-4c76-b9d4-258f93877421"),
                            Descricao = "Sorvete",
                            PrecoUnitario = 9.99m,
                            Quantidade = 2
                        });
                });

            modelBuilder.Entity("G64.PedidoAPI.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b470c527-cea5-47e3-8e78-3808a618f815"),
                            Data = new DateTime(2024, 5, 21, 23, 9, 29, 826, DateTimeKind.Local).AddTicks(4924),
                            Status = 0,
                            Total = 29.97m
                        },
                        new
                        {
                            Id = new Guid("2676c7e1-cee2-4c19-828e-16c0f26f3b9c"),
                            Data = new DateTime(2024, 5, 21, 23, 9, 29, 826, DateTimeKind.Local).AddTicks(4943),
                            Status = 0,
                            Total = 19.98m
                        });
                });

            modelBuilder.Entity("PedidoItemPedido", b =>
                {
                    b.Property<Guid>("PedidosId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ItemPedidosId")
                        .HasColumnType("char(36)");

                    b.HasKey("PedidosId", "ItemPedidosId");

                    b.HasIndex("ItemPedidosId");

                    b.ToTable("PedidoItemPedido");

                    b.HasData(
                        new
                        {
                            PedidosId = new Guid("b470c527-cea5-47e3-8e78-3808a618f815"),
                            ItemPedidosId = new Guid("4111eadd-a800-432b-a0c0-c310f8a39b7f")
                        },
                        new
                        {
                            PedidosId = new Guid("b470c527-cea5-47e3-8e78-3808a618f815"),
                            ItemPedidosId = new Guid("1ba15591-fc3b-4613-8aa3-051e6e60e17d")
                        },
                        new
                        {
                            PedidosId = new Guid("b470c527-cea5-47e3-8e78-3808a618f815"),
                            ItemPedidosId = new Guid("272e6795-a488-4d52-a28c-363044567ef9")
                        },
                        new
                        {
                            PedidosId = new Guid("2676c7e1-cee2-4c19-828e-16c0f26f3b9c"),
                            ItemPedidosId = new Guid("900d293e-6190-4c76-b9d4-258f93877421")
                        });
                });

            modelBuilder.Entity("PedidoItemPedido", b =>
                {
                    b.HasOne("G64.PedidoAPI.Models.ItemPedido", null)
                        .WithMany()
                        .HasForeignKey("ItemPedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("G64.PedidoAPI.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
