version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tech-challenge-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - tech-challenge-fiap

  pedido-service:
    build: .
    ports:
      - "8085:80"
    environment:
      DB_HOST: db
      DB_NAME: tech-challenge-db
      DB_USERNAME: myuser
      DB_PASSWORD: secret
    networks:
      - tech-challenge-fiap
    depends_on:
      - db

networks:
  tech-challenge-fiap:
    driver: bridge
