version: '3.8'

services:
  app:
    image: seu-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    depends_on:
      - migrate

  migrate:
    image: seu-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet ef database update
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    entrypoint: ["/bin/bash", "-c", "dotnet ef database update && exit 0"]
# version: '3.9'

# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     container_name: sqlserver
#     environment:
#       - SA_PASSWORD=G64@soatfiap
#       - ACCEPT_EULA=Y
#     ports:
#       - "1433:1433"
#     volumes:
#       - sqlserverdata:/var/opt/mssql
#   pedidoapi:
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - "8080:80"
#     depends_on:
#       - sqlserver
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - DBHOST=db
#       - ASPNETCORE_URLS=http://+:80
#     entrypoint: ["dotnet", "G64.PedidoAPI.dll"]

# volumes:
#   sqlserverdata:

